export const SET_MASTER = "SET_MASTER";
export const ADD_MASTER = "ADD_MASTER";
export const REMOVE_MASTER = "REMOVE_MASTER";
export const UPDATE_MASTER = "UPDATE_MASTER";
export const SET_POPUP_ADD_DISPLAY_MASTER = "SET_POPUP_ADD_DISPLAY_MASTER";
export const SET_POPUP_EDIT_DISPLAY_MASTER = "SET_POPUP_EDIT_DISPLAY_MASTER";