export const SET_CITY = "SET_CITY";
export const ADD_CITY = "ADD_CITY";
export const REMOVE_CITY = "REMOVE_CITY";
export const UPDATE_CITY = "UPDATE_CITY";
export const SET_POPUP_ADD_DISPLAY = "SET_POPUP_ADD_DISPLAY";
export const SET_POPUP_EDIT_DISPLAY = "SET_POPUP_EDIT_DISPLAY";

