export const SET_MASTER_FOR_CITY = 'SET_MASTER_FOR_CITY';
export const SET_MASTER_LOADED = 'SET_MASTER_LOADED';
export const SET_ORDER = 'SET_ORDER';
export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const SET_POPUP_CREATE_DISPLAY_ORDER = 'SET_POPUP_CREATE_DISPLAY_ORDER';
